// <auto-generated />
namespace Tresana.Data.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class testUser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(testUser));
        
        string IMigrationMetadata.Id
        {
            get { return "201605100430065_testUser"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
