// <auto-generated />
namespace Tresana.Data.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class updatedRelation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatedRelation));
        
        string IMigrationMetadata.Id
        {
            get { return "201605100358205_updatedRelation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
